# Generated by Django 5.2 on 2025-05-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Telegram chat ID"
            ),
        ),
    ]
