# Generated by Django 5.2 on 2025-05-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_telegram_chat_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="User name"
            ),
        ),
    ]
