# Generated by Django 5.2 on 2025-05-11 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
    ]
