# Generated by Django 5.2 on 2025-04-19 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "habit_name",
                    models.CharField(max_length=300, verbose_name="Habit name"),
                ),
                ("habit_place", models.TextField(verbose_name="Place to have a habit")),
                (
                    "habit_time_start",
                    models.TimeField(auto_now=True, verbose_name="Timeset for a habit"),
                ),
                ("habit_action", models.TextField(verbose_name="Action for a habit")),
                (
                    "habit_time_duration",
                    models.PositiveSmallIntegerField(
                        verbose_name="Timme duration for a habit"
                    ),
                ),
                ("habit_is_public", models.BooleanField(default=False)),
                (
                    "habit_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habit_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Habit",
                "verbose_name_plural": "Habits",
            },
        ),
    ]
