# Generated by Django 5.2 on 2025-04-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="habit_period",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Period for a habit (in days)"
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="habit_reward",
            field=models.TextField(
                blank=True, null=True, verbose_name="Reward for a habit"
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="nice_habit",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="habit",
            name="habit_time_duration",
            field=models.PositiveSmallIntegerField(
                verbose_name="Time duration for a habit"
            ),
        ),
    ]
