# Generated by Django 5.2 on 2025-04-20 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_habit_habit_period_habit_habit_reward_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="nice_habit",
        ),
    ]
