# Generated by Django 5.2 on 2025-04-20 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_remove_habit_nice_habit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NiceHabit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nice_habit_name",
                    models.CharField(max_length=300, verbose_name="Nice Habit name"),
                ),
                ("is_nice_habit", models.BooleanField(default=False)),
                (
                    "nice_habit_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nice_habit_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Nice Habit",
                "verbose_name_plural": "Nice Habits",
            },
        ),
        migrations.AddField(
            model_name="habit",
            name="nice_habit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nice_habit",
                to="habits.nicehabit",
            ),
        ),
    ]
