# Generated by Django 5.2 on 2025-04-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_nicehabit_habit_nice_habit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="nice_habit",
        ),
        migrations.AddField(
            model_name="habit",
            name="nice_habit",
            field=models.ManyToManyField(
                blank=True, related_name="nice_habit", to="habits.nicehabit"
            ),
        ),
    ]
