# Generated by Django 5.2 on 2025-04-20 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0005_remove_habit_nice_habit_habit_nice_habit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="nice_habit",
        ),
        migrations.AddField(
            model_name="habit",
            name="is_nice_habit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="habit",
            name="nice_habit_name",
            field=models.CharField(
                default="Draft", max_length=300, verbose_name="Habit name"
            ),
        ),
        migrations.AlterField(
            model_name="nicehabit",
            name="nice_habit_user",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nice_habit_user",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
