# Generated by Django 5.2 on 2025-04-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0006_remove_habit_nice_habit_habit_is_nice_habit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="is_habit_reward",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="NiceHabit",
        ),
    ]
