# Generated by Django 5.2 on 2025-04-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0007_habit_is_habit_reward_delete_nicehabit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="habit_reward",
            field=models.TextField(default="Tea", verbose_name="Reward for a habit"),
        ),
    ]
