# Generated by Django 5.2 on 2025-04-20 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0008_alter_habit_habit_reward"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="nice_habit_name",
        ),
    ]
