# Generated by Django 5.2 on 2025-04-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0009_remove_habit_nice_habit_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="nice_habit_name",
            field=models.CharField(
                default="Draft", max_length=300, verbose_name="Habit name"
            ),
        ),
    ]
