# Generated by Django 5.2 on 2025-04-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0010_habit_nice_habit_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="nice_habit_name",
            field=models.CharField(
                blank=True, default="Draft", max_length=300, verbose_name="Habit name"
            ),
        ),
    ]
