# Generated by Django 5.2 on 2025-04-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0011_alter_habit_nice_habit_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="is_habit_started",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="habit",
            name="habit_reward",
            field=models.TextField(
                blank=True, default="Tea", verbose_name="Reward for a habit"
            ),
        ),
    ]
