# Generated by Django 5.2 on 2025-05-08 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0012_habit_is_habit_started_alter_habit_habit_reward"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="habit_time_start",
        ),
        migrations.RemoveField(
            model_name="habit",
            name="is_habit_started",
        ),
    ]
