# Generated by Django 5.2 on 2025-05-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0014_habit_related_habit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="habit_reward",
            field=models.TextField(blank=True, verbose_name="Reward for a habit"),
        ),
    ]
