# Generated by Django 5.2 on 2025-05-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0015_alter_habit_habit_reward"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="habit_time_start",
            field=models.TimeField(auto_now=True, verbose_name="Timeset for a habit"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="nice_habit_name",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Habit name"
            ),
        ),
    ]
