# Generated by Django 5.2 on 2025-05-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0016_habit_habit_time_start_alter_habit_nice_habit_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="habit_time_start",
            field=models.TimeField(verbose_name="Timeset for a habit"),
        ),
    ]
