# Generated by Django 5.2 on 2025-05-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0017_alter_habit_habit_time_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="date",
            field=models.DateTimeField(auto_now=True, verbose_name="Date"),
        ),
    ]
