# Generated by Django 5.2 on 2025-05-10 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0018_habit_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="habit",
            old_name="date",
            new_name="habit_date",
        ),
    ]
