# Generated by Django 5.2 on 2025-05-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0019_rename_date_habit_habit_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="habit_date",
            field=models.DateTimeField(verbose_name="Date"),
        ),
    ]
