# Generated by Django 5.2 on 2025-05-10 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0020_alter_habit_habit_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="habit_time_start",
        ),
    ]
