# Generated by Django 5.2 on 2025-05-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0021_remove_habit_habit_time_start"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="is_habit_reward",
        ),
        migrations.RemoveField(
            model_name="habit",
            name="nice_habit_name",
        ),
        migrations.AlterField(
            model_name="habit",
            name="habit_reward",
            field=models.TextField(
                blank=True, null=True, verbose_name="Reward for a habit"
            ),
        ),
    ]
