# Generated by Django 5.2 on 2025-05-11 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0022_remove_habit_is_habit_reward_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="habit_user",
            field=models.ForeignKey(
                default=43,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="habit_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
